---
# Source: datadog/templates/secret-cluster-agent-token.yaml
apiVersion: v1
kind: Secret
metadata:
  name: datadog-cluster-agent
  namespace: default
  labels:
    helm.sh/chart: 'datadog-2.30.10'
    app.kubernetes.io/name: "datadog"
    app.kubernetes.io/instance: "datadog"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
type: Opaque
data:
  token: "QlNOTkJWRDRYQU9va1VSSzJGazlUemNCWGZKRHV4Mk4="
